services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379

  redis:
    image: "redis:alpine"
    restart: unless-stopped
    ports:
      - "6379:6379"